### ISSUE TITLE
flash.utils package

### ISSUE THREAD

**Issue by zwetan** [Corsaair/redtamarin#100]
Do a complete implementation of the whole `flash.utils` package
see for reference [documentation](http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/utils/package-detail.html)

already implemented in avmplus
- [x] IDataInput interface
- [x] IDataOutput interface
- [x] IExternalizable interface
- [x] ByteArray class
- [x] CompressionAlgorithm class
- [x] Dictionary class
- [x] Endian class
- [x] Proxy class

this is meta issue related to
- [x] describeType() function
- [x] getDefinitionByName() function
- [x] getQualifiedClassName() function
- [x] getQualifiedSuperclassName() function
- [x] getTimer() function
- [x] #101 implement flash.utils.Timer
- [x] #102 implement setInterval/clearInterval and setTimeout/clearTimeout
- [x] #103 implement escapeMultiByte() function
- [x] #104 implement unescapeMultiByte() function
