### ISSUE TITLE
API Capabilities Overview

### ISSUE THREAD

**Issue by zwetan** [Corsaair/redtamarin#137]
Listing of Capabilities related to AVM2/Redtamarin

  - [x] #146 Accelerometer (`Accelerometer.isSupported`)
  - [x] #147 Accessibility (`Capabilities.hasAccessibility`)
  - [x] #148 Acoustic echo cancelation (`Microphone.getEnhancedMicrophone()`)
  - [x] #138 ActionScript 2
  - [x] #139 CacheAsBitmap matrix
  - [x] #149 Camera (`Camera.isSupported`)
  - [x] #150 CameraRoll
  - [x] #151 CameraUI (`CameraUI.isSupported`)
  - [x] #140 Captive runtime bundles
  - [x] #152 ContextMenu (`ContextMenu.isSupported`)
  - [ ] #153 DatagramSocket (`DatagramSocket.isSupported`)
  - [x] #154 DeviceRotation (`DeviceRotation.isSupported`)
  - [x] #155 DockIcon (`NativeApplication.supportsDockIcon`)
  - [x] #156 Drag-and-drop (`NativeDragManager.isSupported`)
  - [ ] #157 EncryptedLocalStore (`EncryptedLocalStore.isSupported`)
  - [x] #158 Flash Access (`DRMManager.isSupported`)
  - [x] #159 GameInput (`GameInput.isSupported`)
  - [x] #160 Geolocation (`Geolocation.isSupported`)
  - [x] #161 HTMLLoader (`HTMLLoader.isSupported`)
  - [x] #162 IME (`IME.isSupported`)
  - [ ] #163 LocalConnection (`LocalConnection.isSupported`)
  - [x] #164 Microphone (`Microphone.isSupported`)
  - [x] #165 Multichannel audio (`Capabilities.hasMultiChannelAudio()`)
  - [x] #141 Native Extensions
  - [x] #166 NativeMenu (`NativeMenu.isSupported`)
  - [ ] #167 NativeProcess (`NativeProcess.isSupported`)
  - [x] #168 NativeWindow (`NativeWindow.isSupported`)
  - [ ] #169  NetworkInfo (`NetworkInfo.isSupported`)
  - [ ] #170 Open files with default application
  - [ ] #171 PrintJob (`PrintJob.isSupported`)
  - [ ] #172 SecureSocket (`SecureSocket.isSupported`)
  - [ ] #173 ServerSocket (`ServerSocket.isSupported`)
  - [x] #142 Shader
  - [x] #174 Stage3D (`Stage.stage3Ds.length`)
  - [x] #175 Stage orientation (`Stage.supportsOrientationChange`)
  - [x] #143 StageVideo
  - [ ] #176 StageWebView (`StageWebView.isSupported`)
  - [ ] #177 Start application at login (`NativeApplication.supportsStartAtLogin`)
  - [ ] #178 StorageVolumeInfo (`StorageVolumeInfo.isSupported`)
  - [x] #144 System idle mode
  - [ ] #179 SystemTrayIcon (`NativeApplication.supportsSystemTrayIcon`)
  - [x] #145 Text Layout Framework input
  - [x] #180 Updater (`Updater.isSupported`)
  - [ ] #181  XMLSignatureValidator (`XMLSignatureValidator.isSupported`)

**Comment by zwetan** [comment]
8 planed (by order of preference)
  - #153 DatagramSocket
  - #173 ServerSocket
  - #167 NativeProcess
  - #163 LocalConnection
  - #169 NetworkInfo
  - #178 StorageVolumeInfo
  - #157 EncryptedLocalStore
  - #172 SecureSocket

6 maybe (by order of preference)
  - #170 Open files with default application
  - #177 Start application at login
  - #176 StageWebView
  - #171 PrintJob 
  - #179 SystemTrayIcon
  - #181 XMLSignatureValidator

planed have the priority
