### ISSUE TITLE
flash.net package

### ISSUE THREAD

**Issue by zwetan** [Corsaair/redtamarin#78]
Do a first draft implementation of the whole `flash.net` package
see for reference [documentation](http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/net/package-detail.html)

Goal
- focus on sockets
- ~~ignore events, use callback~~
  no we do use events, but shell package classes do use function callbacks
- ~~implementation in [betalib](https://github.com/Corsaair/betalib)~~
  may happen but sometimes it is easier do impl directly in redtamarin

already implemented in avmplus
- [x] IDynamicPropertyOutput interface
- [x] IDynamicPropertyWriter interface
- [x] DynamicPropertyOutput class
- [x] ObjectEncoding class
- [x] registerClassAlias() function
- [x] getClassByAlias() function

this is meta issue related to
- [ ] #115 implement sendToURL() function
- [ ] #116 implement navigateToURL() function
- [ ] #108 implement FileReference
- [ ] #110 implement URLRequest
- [ ] #111 implement URLRequestDefaults
- [ ] #112 implement URLRequestHeader
- [ ] #113 implement URLRequestMethod
- [ ] #114 implement URLVariables
- [ ] #47 implement LocalConnection (google code Issue 8)
- [ ] #48 implement flash.net.SharedObject (google code Issue 9)
- [ ] #49 implement flash.net.Socket (google code Issue 10)
- [ ] #50 implement SocketServer (google code Issue 11)
- [ ] #80 native socket options
- [ ] #81 cleanup C.sys.select

**Comment by zwetan** [comment]
~~see this [gist](https://gist.github.com/zwetan/565109f1138cac00795e) as a starting example~~
nope use the event system instead
