### ISSUE TITLE
flash.events package

### ISSUE THREAD

**Issue by zwetan** [Corsaair/redtamarin#82]
Do a first draft implementation of the whole `flash.events` package
see for reference [documentation](http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/events/package-detail.html)

Goal
- focus on the easy stuff  
  eg. keep `Event` class as mock but implement all the child classes
- for `Event` and `EventDispatcher` implementation  
  do a very basic simple one, provide internal hooks
- ~~implementation in [betalib](https://github.com/Corsaair/betalib)~~

this is meta issue related to
- [x] IEventDispatcher interface
- [x] #105 implement Event
- [x] EventPhase class
- [x] #106 implement EventDispatcher
- [x] OutputProgressEvent class
- [x] ProgressEvent class
- [x] TextEvent class
- [x] ErrorEvent class
- [x] IOErrorEvent class
- [x] TimerEvent class
- [x] #83 native timer callback
- [x] #46 implement events (google code Issue 4)
- [ ] #84 test a worker event loop

**Comment by zwetan** [comment]
once we have a native timer callback we should be able to create a non-blocking event loop

eg this is blocking

``` as3
while( true )
{
    // event loop
}

// code not executed here
```

this should be non-blocking

``` as3
function myEventLoop():void
{
    // event loop
}

Program.setTimerListener( 1, myEventLoop );

// code executed here

// ... addEventListener/removeEventListener/ native/internal events dispatch

// event loop kick-in at 1 sec

// ...

// event loop kick-in at 2 sec

// ... addEventListener/removeEventListener/ native/internal events dispatch

// event loop kick-in at 3 sec

// etc.

// program flow continue till exit()
// option to block and wait all events complete before exit
```

**Comment by zwetan** [comment]
we have events working

a main interface `shell.async.IEventLoop` (probably will be renamed to `ILoop`
a basic `Loop` implementation

primordial worker run the `MainLoop` class
and child workers run the `WorkerLoop` class

main differences are things that the main worker can do that child workers can not do
for example
  - catching signals like SIGINT, SIGTERM, etc.
  - synchronising workers events
  - etc.

now the work is to find good balance to be able to spawn worker to do async tasks
but receive back events into the main worker

for ex: with `flash.net.Socket`
`connect()` spawn a worker that use BSD socket `connect()`in  blocking mode
but in parallel we run a timers to implement the `Socket.timeout` behaviour

scenarios are
  - if connect happen, child worker notify main worker and the connect event is dispatched
  - if timeout kickin before connect happen, main worker terminate the child worker
    and another event is dispatched (? not sure yet, need to test with a simple AIR app in parallel)

at first, we might allow to create `flash.net.Socket` only from the main worker and not from child workers, TDB

focus is `flash.filesystem` and `flash.net`
