### ISSUE TITLE
AVMGlue API

### ISSUE THREAD

**Issue by zwetan** [Corsaair/redtamarin#89]
Here the listing of all issues related to the AVMGlue API

Discussion
- [ ] #75 Flash/AIR API AVMGlue
- [ ] #137 API Capabilities Overview
  - [ ] #153 DatagramSocket
  - [ ] #173 ServerSocket
  - [ ] #167 NativeProcess
  - [ ] #163 LocalConnection
  - [ ] #169 NetworkInfo
  - [ ] #178 StorageVolumeInfo
  - [ ] #157 EncryptedLocalStore
  - [ ] #172 SecureSocket

Flash 9.0 API
- [ ] flash.accessibility
- [x] flash.concurrent
- [ ] flash.display
- [x] #109 flash.errors package
  - [x] `DRMManagerError`
  - [x] `EOFError`
  - [x] `IllegalOperationError`
  - [x] `InvalidSWFError`
  - [x] `IOError`
  - [x] `MemoryError`
  - [x] `PermissionError`
  - [x] `ScriptTimeoutError`
  - [x] `SQLError`
  - [x] `SQLErrorOperation`
  - [x] `StackOverflowError`
- [ ] #82 flash.events package
  - [x] #83 native timer callback
- [ ] flash.external
- [ ] flash.filters
- [ ] flash.geom
- [ ] flash.media
- [ ] #78 flash.net package
- [ ] flash.net.dns
- [ ] flash.net.drm
- [ ] flash.printing
- [x] flash.profiler
  - [x] `profile()`
  - [x] `showRedrawRegions()`
  - [x] `Telemetry`
- [x] flash.sampler
  - [x] `clearSamples()`
  - [x] `getGetterInvocationCount()`
  - [x] `getInvocationCount()`
  - [x] `getLexicalScopes()`
  - [x] `getMasterString()`
  - [x] `getMemberNames()`
  - [x] `getSampleCount()`
  - [x] `getSamples()`
  - [x] `getSavedThis()`
  - [x] `getSetterInvocationCount()`
  - [x] `getSize()`
  - [x] `isGetterSetter()`
  - [x] `pauseSampling()`
  - [x] `sampleInternalAllocs()`
  - [x] `setSamplerCallback()`
  - [x] `startSampling()`
  - [x] `stopSampling()`
  - [x] `DeleteObjectSample`
  - [x] `NewObjectSample`
  - [x] `Sample`
  - [x] `StackFrame`
- [ ] #121 flash.system package 
  - [x] `fscommand()`
  - [x] `ApplicationDomain`
  - [x] `ApplicationInstaller`
  - [x] `ApplicationInstallerMode`
  - [x] `AuthorizedFeatures`
  - [x] `AuthorizedFeaturesLoader`
  - [x] `Capabilities`
  - [x] `ImageDecodingPolicy`
  - [x] `IME`
  - [x] `IMEConversionMode`
  - [x] `JPEGLoaderContext`
  - [x] `LoaderContext`
  - [x] `MessageChannel`
  - [x] `MessageChannelState`
  - [x] `Security`
  - [x] `SecurityDomain`
  - [x] `SecurityPanel`
  - [x] `SecurityPrivilege`
  - [x] `System`
  - [x] `SystemUpdater`
  - [x] `SystemUpdaterType`
  - [x] `TouchscreenType`
  - [ ] `Worker`
  - [ ] `WorkerDomain`
  - [ ] `WorkerState`
- [ ] flash.text
- [ ] flash.text.engine
- [x] flash.text.ime
  - [x] `IIMEClient`
  - [x] `CompositionAttributeRange`
- [ ] flash.ui
- [x] #100 flash.utils package
  - [x] `clearInterval()`
  - [x] `clearTimeout()`
  - [x] `describeType()`
  - [x] `escapeMultiByte()`
  - [x] `getDefinitionByName()`
  - [x] `getQualifiedClassName()`
  - [x] `getQualifiedSuperclassName()`
  - [x] `getTimer()`
  - [x] `setInterval()`
  - [x] `setTimeout()`
  - [x] `unescapeMultiByte()`
  - [x] `IDataInput`
  - [x] `IDataOutput`
  - [x] `IExternalizable`
  - [x] `ByteArray`
  - [x] `CompressionAlgorithm`
  - [x] `Dictionary`
  - [x] `Endian`
  - [x] `Proxy`
  - [x] `Timer`
- [ ] flash.xml

AIR 1.0 API
- [ ] air.desktop
- [ ] air.net
- [ ] air.update
- [ ] air.update.events
- [ ] flash.data
- [ ] flash.desktop
- [ ] #107 flash.filesystem package
- [ ] flash.html
- [ ] flash.security

Other API
- [x] avm2.intrinsics.memory
  - [ ] #68 review avm2.intrinsics.memory
  - [x] `casi32()`
  - [x] `lf32()`
- [x] avmplus
  - [ ] #182 Supports for native formats
  - [ ] #183 Supports for HTTP
- [x] adobe.utils
  - [x] `MMEndCommand()`
  - [x] `MMExecute()`
  - [x] `CustomActions`
  - [x] `ProductManager`
  - [x] `XMLUI`
- [ ] com.adobe.viewsource
- [x] flash.debugger
  - [x] `enterDebugger()`
- [x] flash.trace
  - [x] `Trace`

misc (non SWF9 API)
- [x] #38 impl flash.crypto.generateRandomBytes
- [ ] flash.display3D
- [ ] flash.display3D.textures
- [ ] flash.globalization
- [ ] flash.notifications
- [x] flash.permissions
  - [x] `PermissionStatus`
- [x] flash.sensors

----

- [x] When a package is checked  it means
  - all the definitions class, interface, function, etc. are implemented
  - documentation reviewed
    eg. all asdoc is done
  - capabilities reviewed
    eg. does it involve an API in Capabilities
  - worker reviewed
    eg. does it involve "Unsupported in Background Workers"
    and/or "APIs with behavioral changes in background Workers"
  - it can be either a **Stub** (NO-OP) or a full implementation
